### ISSUE TITLE
preprocess.py 실행 시 이슈 발생

### ISSUE THREAD

**Issue by ghost** [HGU-DLLAB/Korean-FastSpeech2-Pytorch#17]
안녕하세요, 음성합성 공부 중 문제가 발생해 질문 드립니다. 데이터 전처리 과정 진행 시 아래와 같은 문제가 발생합니다.
어떤 부분이 잘못된 것인지 알 수 있을까요?

`
Traceback (most recent call last):
  File "preprocess.py", line 46, in <module>
    main()
  File "preprocess.py", line 41, in main
    train, val = kss.build_from_path(in_dir, out_dir, meta)
  File "/home/username/문서/Korean-FastSpeech2-Pytorch/data/kss.py", line 45, in build_from_path
    ret = process_utterance(in_dir, out_dir, basename, scalers)
  File "/home/username/문서/Korean-FastSpeech2-Pytorch/data/kss.py", line 95, in process_utterance
    fo, _ = pw.dio(wav.astype(np.float64), hp.sampling_rate, frame_period=hp.hop_length/hp.sampling_rate*1000)
  File "pyworld/pyworld.pyx", line 93, in pyworld.pyworld.dio
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

**Comment by Jackson-Kang** [comment]
@UKSX 님께,


안녕하세요, @UKSX 님.

input wav의 channel이 mono인가요 stereo인가요?..
만약 stereo라면, mono로 converting 하신 후 시도해보시는 것을 권장드립니다.

감사합니다.

**Comment by ghost** [comment]
감사합니다! 이슈는 닫겠습니다.

**Comment by Jackson-Kang** [comment]
@UKSX 님께,

부족한 답변이 도움이 되었으면 좋겠습니다.
감사합니다.
